api/urls.py
from django.urls import path
from .views import NoteLIstCreateAPIView, NoteDetailAPIView 

app_name = 'api'


urlpatterns = [
    path('notes/',NoteLIstCreateAPIView.as_view(), name='home'),
    path('notes/<uuid:product_id>/',NoteDetailAPIView.as_view(), name='note_detail'),

    
]

home_page/urls.py
from django.urls import path
from .views import home_page_veiw

urlpatterns = [
    path('', home_page_veiw, name='home'),
    
]

note/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView
from api.views import CreateUserView

urlpatterns = [
    path('site/main/url/', admin.site.urls),
    path('api/', include('api.urls')),
    path('api/user/register/',CreateUserView.as_view(), name='register'),
    path('api/token/',TokenObtainPairView.as_view(), name='token'),
    path('api/token/refresh/',TokenRefreshView.as_view(), name='token-refresh'),
    path('api-auth/', include('rest_framework.urls')),
    path('', include('home_page.urls')), 

]

api/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid

class Note(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    content = models.TextField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='notes')
    
    def __str__(self) :
        return f'{self.content[0:50]} by {self.author.username}'
    

home_page/models.py
from django.db import models

# Create your models here.

api/views.py
from rest_framework.response import Response
from rest_framework.decorators import api_view
from .serializers import NoteSerializer, UserSerializer
from .models import Note
from rest_framework import status, generics
from rest_framework.permissions import AllowAny, IsAuthenticated
from django.contrib.auth.models import User

class NoteLIstCreateAPIView(generics.ListCreateAPIView):
    queryset = Note.objects.all()
    serializer_class = NoteSerializer
    permission_classes = [IsAuthenticated]
    
    def get_queryset(self):
        user = self.request.user
        return Note.objects.filter(author=user)
    
    def perform_create(self, serializer):
        if serializer.is_valid():
            serializer.save(author=self.request.user)
        else:
            print(serializer.errors)
    
class NoteDetailAPIView(generics.RetrieveUpdateDestroyAPIView):
    queryset = Note.objects.all().order_by('-id')
    serializer_class = NoteSerializer
    lookup_url_kwarg = 'product_id'
  


class CreateUserView(generics.CreateAPIView):
   queryset = User.objects.all()
   serializer_class = UserSerializer
   permission_classes = [AllowAny]

home_page/views.py
from django.shortcuts import render

def home_page_veiw(request):
    return render(request, 'home.html')

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <title>
        {% block title %}

        {% endblock title %}
    </title>
  </head>
  <body>
    <div class="container">
        {% block content %}

        {% endblock content %}
        </div>  
  </body>
</html>

templates/home.html
{% extends "base.html" %}
{% load static %}


{% block title %} Home {% endblock %}

{% block content %}


{% if user.is_authenticated %}
    <h2>Hello {{user}}</h2>
    <div class="inside-container">
        <a href="api/notes">Go to api lists</a>

    </div>
{% else %}
    <h2>You are not logged in</h2>
    <div class="inside-container">
        <a href="api-auth/login/?next=/api/notes/" >Log In</a>
    </div>
{% endif %}

<div>
    <h2>Links </h2>
    <div class="inside-container">
        <a href="{%url 'api:home'%}">API - Application Programming Interface</a>
    </div>
    <div class="inside-container">
        <a href="{%url 'register'%}">User Register</a>
    </div>
    <div class="inside-container">
        <a href="https://sleepy-ridge-47471-b1a97be9fc1d.herokuapp.com/api-auth/login/?next=/api/notes/">Login</a>
    </div>
    <div class="inside-container">
        <a href="{%url 'token'%}">Token</a>
    </div>
    <div class="inside-container">
        <a href="{%url 'token-refresh'%}">Token Refresh</a>
    </div>
    <div class="inside-container">
        <a href="https://sleepy-ridge-47471-b1a97be9fc1d.herokuapp.com/site/main/url/login/?next=/site/main/url/">Admin Panel</a>
    </div>
</div>











{% endblock %}